### ISSUE TITLE
Update browser for gnomAD v4.1 (checklist)

### ISSUE THREAD

**Issue by ch-kr** [broadinstitute/gnomad-browser#1444]
Ticket to track various v4.1 data loading / update requests

### Loading requests:
- [x] #1439 | (@phildarnowsky-broad) Update code parsing SV and CNV files to accommodate updates, including updated metrics order, updated genetic ancestry terms, update from using gender to sex karyotype and reload SV, CNVs
- [x] (@rileyhgrant) Load demo with PCSK9 (see [thread](https://the-tgg.slack.com/archives/C018PB68VU5/p1710511485038629)) to get feedback on new flags below
- [x] (@rileyhgrant) Load demo that contains only new gene constraint results (HT path shared [here](https://the-tgg.slack.com/archives/C018PB68VU5/p1710510559427449); `gs://gnomad/v4.1/constraint/metrics/gnomad.v4.1.constraint_metrics.ht`)
- [x] #1463 | (@rileyhgrant, @nadeaujoshua)  Reload short variant exome and genome data
- [x] #1443 | (@rileyhgrant) Update downloads page links to point to new data
- [x] (riley to merge PRs, work done by methods team -- thank you!) Apply changes to help pages; current PRs:
    - [x] #1430 | HT help page -- Qin added a few minor edits due to the slightly tweaked joint freq HT schema 
    - [x] #1433 | v4.0>v4.1 updates -- this PR has been approved and is ready to go (note that I added a minor update to the dataset selection page on Apr 4)
    - [x] #1456 | Exome capture regions
    - [x] #1465 | describe new joint freq stats
    - [x] #1476 | Add new flags to flags help page (new PR)
    - [x] #1488 | Update name of v4 non-UKB subset in dataset selection help page
    - [x] #1492 | Update joint frequency stats page to reflect different tests used -- PR approved/ready
    - [x] #1494 | Allele count help page -- PR approved/ready
- [x] #1448 (@phildarnowsky-broad)| Make non-ukbb a selectable subset

### Updates:
- [x] #1423 | (@rileyhgrant) Add new flag indicating when a variant was not called in any data type
- [x] #1442 | (@rileyhgrant) Add new flag for variants with discrepant frequencies between the exomes and genomes
- [x] #1440 | (@rileyhgrant) Update stats page to include number of samples in the two of the v4.0 exomes subsets
- [x] #1458 | (@rileyhgrant) Not necessarily v4.1, but update typos on stats page
- [ ] (no issue) | (@rileyhgrant) Update stats page to include average number of SNVs per person (still being calculated) -- edit to add that this has been pushed to post-v4.1 (hoping to have shortly afterwards)
- [x] https://github.com/broadinstitute/gnomad-blog/pull/153 | -- Blog post is approved/ready

### Feedback
- [x] #1475 | (@rileyhgrant) ticket tracking feedback on v4.1 demo browser

Will add updates if I've missed anything and as we create links for some of the topics above!

Also including [v4.1 release checklist](https://docs.google.com/document/d/1ZGI9cITORzxcFzVFcDwb_4s63cfFxImfuEI0Ck5iNII/edit)

**Comment by rileyhgrant** [comment]
Closing as completed, will open tickets for cleanup as needed.
