### ISSUE TITLE
Implement variant page

### ISSUE THREAD

**Issue by nawatts** [broadinstitute/gnomad-browser#156]
The variant page is currently part of the Flask app in https://github.com/macarthur-lab/gnomad_browser. It needs to be added to the SPA.

* [x] Routing
* [x] Exome/genome/total table
* [x] Quality metrics graphs
* [x] Transcript annotations
* [x] Population frequency table
* [x] Read data visualization (#27)
* [x] Filters
* [x] Flags
* [x] Multiallelic variants
